const data = {
    products: [
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 80,
            brand: 'Adidas',
            rating: 4.2,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 90,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Golf Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 90,
            brand: 'Oliver',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Smart looking pants',
        },
        {
            name: 'Fit Pants',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 95,
            brand: 'Zara',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pants',
        },
        {
            name: 'Classic Pants',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 75,
            brand: 'Casely',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pants',
        },    
    ],
};

export default data;